postgres_conn:
  target: dev
  outputs:
    dev:
      type: postgres
      host: database-2.cnlhrwdfjgkj.ap-south-1.rds.amazonaws.com
      user: revathi
      password: medbelle
      port: 5432
      dbname: medbelle
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
     